# FONT
font_family      family="Hack Nerd Font Mono"
# font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10
# adjust_line_height  1

# END_FONT

allow_remote_control yes
include ./kitty-themes/themes/Afterglow.conf
cursor_shape block
shell_integration no-cursor
cursor_blink_interval 0
macos_titlebar_color #303237

pixel_scroll true

adjust_line_height  110%
# modify_font underline_position +2
box_drawing_scale 0.001, 0.1, 1.5, 2
